# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-node-backend-service
spec:
  type: NodePort
  selector:
    app: my-node-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30007

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-node-backend-service
# spec:
#   type: ClusterIP
#   selector:
#     app: my-node-backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5001