apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-backend
  template:
    metadata:
      labels:
        app: my-node-backend
    spec:
      containers:
        - name: my-node-backend
          image: anshavikhanna/platemate-backend:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "256Mi" # Request 256 MB of memory
            limits:
              memory: "512Mi" # Limit to 512 MB of memory
          # env:
          # - name: MONGO_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: backend-secret
          #       key: mongo-url

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-node-backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-node-backend
#   template:
#     metadata:
#       labels:
#         app: my-node-backend
#     spec:
#       containers:
#         - name: my-node-backend
#           image: anshavikhanna/platemate-backend:latest
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 5001
#           env:
#             - name: CORS_ORIGIN
#               value: "http://localhost:30008,http://my-react-app-service"
#           resources:
#             requests:
#               memory: "256Mi"
#             limits:
#               memory: "512Mi"